name: Generate Python Documentation [PDF]

on:
  # push:
  #   branches:
  #     - main
  #     - dev
  workflow_dispatch:

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen make texlive texlive-latex-extra texlive-fonts-recommended latexmk
      
      - name: Pull latest changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git pull
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate documentation
        run: |
          ls -la
          doxygen Doxyfile

      - name: Process documentation
        run: |
          cd doc/latex
          make
          cp refman.pdf ../documentazione.pdf
          cd ../

      - name: Commit and push documentation
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add doc/documentazione.pdf
          git commit -m "Aggiornata documentazione [PDF]"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}