name: 'Docker build image test'

on:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build & Run Docker image
        run: |
          docker compose build
